name: CI TS Calendar Project


on: 
  push: 
    branches: 
      - '**' 
  pull_request: 
    branches: 
      - '**' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Compile TypeScript
      - name: Compile TypeScript
        run: npm run build

      # Step 5: Run tests (if you have any)
      # - name: Run tests
      #   run: npm test
